services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: keskonmange
      POSTGRES_PASSWORD: keskonmange
      POSTGRES_DB: keskonmange
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
