enum price_range {
  EUR_1
  EUR_2
  EUR_3
  EUR_4
}

enum restaurant_status {
  active
  temporarily_closed
  permanently_closed
}

table accounts {
  user_id text [not null]
  type text [not null]
  provider text [not null]
  provider_account_id text [not null]
  refresh_token text
  access_token text
  expires_at integer
  token_type text
  scope text
  id_token text
  session_state text

  indexes {
    (provider, provider_account_id) [pk]
  }
}

table favorites {
  user_id text [not null]
  restaurant_id text [not null]
  created_at timestamp [not null, default: `now()`]

  indexes {
    (user_id, restaurant_id) [pk]
  }
}

table restaurants {
  id text [pk, not null]
  name text [not null]
  address text [not null]
  latitude real [not null]
  longitude real [not null]
  restaurant_type text
  labels text[]
  price_range price_range
  dine_in boolean [not null, default: true]
  take_away boolean [not null, default: false]
  status restaurant_status [not null, default: 'active']
  photo_cover_url text
  created_by text [not null]
  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
}

table reviews {
  id text [pk, not null]
  restaurant_id text [not null]
  author_id text [not null]
  rating integer [not null]
  comment text
  photo_urls text[]
  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]

  indexes {
    (restaurant_id, author_id) [name: 'reviews_restaurant_id_author_id_unique', unique]
  }
}

table sessions {
  session_token text [pk, not null]
  user_id text [not null]
  expires timestamp [not null]
}

table users {
  id text [pk, not null]
  name text
  email text [not null, unique]
  email_verified timestamp
  image text
}

table verification_tokens {
  identifier text [not null]
  token text [not null]
  expires timestamp [not null]

  indexes {
    (identifier, token) [pk]
  }
}

ref accounts_user_id_users_id_fk: accounts.user_id > users.id [delete: cascade, update: no action]

ref favorites_user_id_users_id_fk: favorites.user_id > users.id [delete: cascade, update: no action]

ref favorites_restaurant_id_restaurants_id_fk: favorites.restaurant_id > restaurants.id [delete: cascade, update: no action]

ref restaurants_created_by_users_id_fk: restaurants.created_by > users.id [delete: no action, update: no action]

ref reviews_restaurant_id_restaurants_id_fk: reviews.restaurant_id > restaurants.id [delete: cascade, update: no action]

ref reviews_author_id_users_id_fk: reviews.author_id > users.id [delete: cascade, update: no action]

ref sessions_user_id_users_id_fk: sessions.user_id > users.id [delete: cascade, update: no action]